AGENT_ISSUE = "agent-issue"
AGENT_REVIEWABLE = "agent-reviewable"
AGENT_CHANGED = "agent-changed"
AGENT_APPROVED = "agent-approved"
MISSING_PR_AFTER_IMPLEMENT = "missing_pr_after_implement"

STATE_LABELS = [
    AGENT_ISSUE,
    AGENT_REVIEWABLE,
    AGENT_CHANGED,
    AGENT_APPROVED,
]

RUNNABLE_STATES = [
    AGENT_ISSUE,
    AGENT_REVIEWABLE,
    AGENT_CHANGED,
]
